name: Lint

on: [push, pull_request]

env:
  NODE_VERSION: lts/iron

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: npm install -g pnpm && pnpm install --frozen-lockfile

      - name: Lint Files
        run: pnpm exec eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0
