name: Unit Test

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

env:
  NODE_VERSION: lts/iron

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install -g pnpm && pnpm install --frozen-lockfile

      - name: Run Unit tests
        run: pnpm test:unit

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: vitest-report
          path: vitest-report/
          retention-days: 30
